apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-app
  labels:
    app: production-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: production-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: production-app
    spec:
      containers:
        - name: production-app
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: production-app-service
spec:
  selector:
    app: production-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
